// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameBusinessowner = "businessowners"

// Businessowner mapped from table <businessowners>
type Businessowner struct {
	ID        string    `gorm:"column:id;primaryKey" json:"id"`
	Nik       string    `gorm:"column:nik" json:"nik"`
	Verified  bool      `gorm:"column:verified" json:"verified"`
	CreatedAt time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName Businessowner's table name
func (*Businessowner) TableName() string {
	return TableNameBusinessowner
}
