// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameDriver = "drivers"

// Driver mapped from table <drivers>
type Driver struct {
	ID                 string    `gorm:"column:id;primaryKey;default:gen_random_uuid()" json:"id"`
	OwnerID            string    `gorm:"column:owner_id" json:"owner_id"`
	RouteID            string    `gorm:"column:route_id" json:"route_id"`
	RegistrationNumber string    `gorm:"column:registration_number" json:"registration_number"`
	Status             string    `gorm:"column:status;default:off" json:"status"`
	AvailableSeats     int32     `gorm:"column:available_seats;default:9" json:"available_seats"`
	CreatedAt          time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt          time.Time `gorm:"column:updated_at;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName Driver's table name
func (*Driver) TableName() string {
	return TableNameDriver
}
