// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameRoute = "routes"

// Route mapped from table <routes>
type Route struct {
	ID               string    `gorm:"column:id;primaryKey;default:gen_random_uuid()" json:"id"`
	RouteName        string    `gorm:"column:route_name" json:"route_name"`
	InitialRoute     string    `gorm:"column:initial_route" json:"initial_route"`
	DestinationRoute string    `gorm:"column:destination_route" json:"destination_route"`
	CreatedAt        time.Time `gorm:"column:created_at" json:"created_at"`
}

// TableName Route's table name
func (*Route) TableName() string {
	return TableNameRoute
}
