openapi: 3.0.3
info:
  title: MikroNet API Documentation
  version: 1.0.0
  description: API documentation for the MikroNet application, covering User, Driver, Business Owner, Government, and Admin functionalities.
servers:
  - url: https://api.mikronet.com/v1
    description: Production server

paths:
  /user/register:
    post:
      summary: User registration
      description: Register a new user account.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                  format: email
                phone:
                  type: string
                password:
                  type: string
                  format: password
              required:
                - name
                - email
                - phone
                - password
      responses:
        '201':
          description: User registered successfully
        '400':
          description: Invalid input data

  /user/verify:
    post:
      summary: Verify user email or phone
      description: Verify user email or phone number using a code.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                code:
                  type: string
                emailOrPhone:
                  type: string
              required:
                - code
                - emailOrPhone
      responses:
        '200':
          description: Verification successful
        '400':
          description: Invalid code or email/phone

  /user/login:
    post:
      summary: User login
      description: Login with email and password.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
                  format: password
              required:
                - email
                - password
      responses:
        '200':
          description: Login successful
        '401':
          description: Invalid credentials

  /user/routes:
    get:
      summary: View Mikrolet routes
      description: Fetch available Mikrolet routes.
      responses:
        '200':
          description: List of routes
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    routeId:
                      type: string
                    routeName:
                      type: string
                    active:
                      type: boolean
        '404':
          description: No routes found

  /user/book:
    post:
      summary: Book a Mikrolet
      description: Book a Mikrolet based on route or destination.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                routeId:
                  type: string
                destination:
                  type: string
              required:
                - routeId
                - destination
      responses:
        '200':
          description: Booking successful
        '400':
          description: Invalid booking details

  /user/history:
    get:
      summary: View travel history
      description: Fetch user travel history.
      responses:
        '200':
          description: List of travel history
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    tripId:
                      type: string
                    date:
                      type: string
                      format: date
                    route:
                      type: string
                    feedback:
                      type: string
        '404':
          description: No history found

  /driver/login:
    post:
      summary: Driver login
      description: Login for drivers with email and password.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
                  format: password
              required:
                - email
                - password
      responses:
        '200':
          description: Login successful
        '401':
          description: Invalid credentials

  /driver/profile:
    get:
      summary: Driver profile
      description: Fetch driver profile details.
      responses:
        '200':
          description: Driver profile details
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                  email:
                    type: string
                  phone:
                    type: string
                  vehicleInfo:
                    type: object
                    properties:
                      vehicleType:
                        type: string
                      licensePlate:
                        type: string
        '401':
          description: Unauthorized

  /government/dashboard:
    get:
      summary: Government dashboard
      description: Fetch data for government dashboard overview.
      responses:
        '200':
          description: Dashboard data
          content:
            application/json:
              schema:
                type: object
                properties:
                  activeVehicles:
                    type: integer
                  registeredUsers:
                    type: integer
                  driverDetails:
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                        age:
                          type: integer
                        status:
                          type: string
                  businessOwners:
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                        contact:
                          type: string
                  feedback:
                    type: array
                    items:
                      type: object
                      properties:
                        rating:
                          type: integer
                        comment:
                          type: string
        '401':
          description: Unauthorized
