openapi: 3.1.0
info:
  title: MikroNet API
  description: "API to serve both mobile and website platform for Mikronet"
  version: 1.0.0
servers:
  - url: http://localhost:3000/
paths:
  /api/register:
    post:
      tags:
        - "Authentication"
      summary: "Register new account"
      requestBody:
        content:
          application/json:
            schema:
              allOf:
                - $ref: '#/components/schemas/profile'
      responses:
        '201':
          description: "Sukses registrasi akun baru"
          content:
            application/json:
              schema:
                type: object
                properties:
                  status: 
                    type: string
                  message:
                    type: string

  /api/login:
    post:
      tags:
        - "Authentication"
      summary: "login akun"
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:  
                  type: string
                kata_sandi:
                  type: string
      responses:
        '201':
          description: "Sukses login akun"
          content:
            application/json:
              schema:
                type: object
                properties:
                  status: 
                    type: string
                  message:
                    type: string

  /api/profil:
    get:
      security:
        - firebaseAuth: []
      summary: "Mendapatkan data profil pengguna"
      responses:
        '200':
          description: "Berhasil mendapatkan data pengguna"
          content:
            application/json:
              schema: 
                type: object
                $ref: '#/components/schemas/profile'
        
        '403':
          description: "Pengguna tidak memiliki hak akses"
          content:
            application/json:
              schema: 
                type: object


  /api/edit-profil:
    patch:
      security:
        - firebaseAuth: []
      summary: "Edit data profil"
      requestBody:
        content:
          application/json:
            schema:
              type: object
              $ref: "#/components/schemas/profile"
      responses:
        '200':
          description: "Berhasil memperbaharui data pengguna"
          content:
            application/json:
              schema: 
                type: object




  /api/ubah-kata-sandi:
    patch:
      security:
        - firebaseAuth: []

  /api/lupa-kata-sandi:
    patch:

  /api/cari-mikro:
    get:

  /api/riwayat:
    get:

  /api/carter:
    post:

  /api/perjalanan:
    get:

  /api/permintaan:
    get:

  /api/pendapatan:
    get:


components:
  securitySchemes:
    firebaseAuth:
      type: http
      scheme: bearer

  schemas:

    profile:
      allOf:
        - $ref: '#/components/schemas/change_profile'
        - $ref: '#/components/schemas/reset_password'

    change_profile:
      type: object
      properties:
        first_name:
          type: string
        last_name:
          type: string
        email:
          type: string
        phone_number:
          type: string
        gender:
          type: string
        date_of_birth:
          type: string
        age:
          type: number

    reset_password:
      type: object
      properties:
        password:
          type: string
        password_confirmation:
          type: string

    change_password:
      allOf:
        - $ref: '#/components/schemas/reset_password'
        - type: object
          properties:
            old_password:
              type: string

    login:
      type: object
      properties:
        email:
          type: string
        password:
          type: string