@startuml

actor User as user
actor Driver as driver

node server {
    node "API Gateway" as api_gateway
    node "profile service" as profile_service
    node "auth service" as authentication_service
    node "driver service" as driver_service
    node "geospatial service" as geospatial_service
}

cloud internet as internet

user <--> internet
driver <--> internet
internet <--> api_gateway
api_gateway <--right--> authentication_service
api_gateway <--> profile_service
api_gateway <--> driver_service
api_gateway <--> geospatial_service


@enduml