volumes:
  kong_data: {}
  kong_prefix_vol:
    driver_opts:
      type: tmpfs
      device: tmpfs
  kong_tmp_vol:
    driver_opts:
      type: tmpfs
      device: tmpfs

services:
  postgres_database:
    image: postgis/postgis
    container_name: postgres_database
    restart: always
    environment:
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: mikronet
    ports:
      - 5432:5432
    healthcheck:
          test: [ "CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}"]
          interval: 10s
          retries: 5
          start_period: 30s
          timeout: 10s
    volumes:
      - ./data/postgis:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - kong-net

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      postgres_database:
        condition: service_healthy
        restart: true
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: gabriel@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 123
    networks:
      - kong-net

#  postgres_database:
#    image: postgres:latest
#    ports:
#      - 5432:5432
#    environment:
#      POSTGRES_PASSWORD: 123
#      POSTGRES_DB: mikronet
#    healthcheck:
#      test: [ "CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}"]
#      interval: 10s
#      retries: 5
#      start_period: 30s
#      timeout: 10s
#    networks:
#      - kong-net
#    volumes:
#      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  driver_service:
    build: driver
    container_name: driver_service
    ports:
      - 8014:8014
    depends_on:
      postgres_database:
        condition: service_healthy
        restart: true
    env_file:
      - authentication/config/auth-config.env
    environment:
      - POSTGRES_HOST=postgres_database
    networks:
      - kong-net

  auth_service:
    build: authentication
    container_name: auth_service
    ports:
      - 8010:8010
    depends_on:
      postgres_database:
        condition: service_healthy
        restart: true
    env_file:
      - authentication/config/auth-config.env
    environment:
      - POSTGRES_HOST=postgres_database
    networks:
      - kong-net

  profile_service:
    build: profiles
    container_name: profile_service
    ports:
      - 8011:8011
    depends_on:
      postgres_database:
        condition: service_healthy
        restart: true
    env_file:
      - authentication/config/auth-config.env
    environment:
      - POSTGRES_HOST=postgres_database
    networks:
      - kong-net

  owner_service:
    build: business_owner
    container_name: owner_service
    ports:
      - 8012:8012
    depends_on:
      postgres_database:
        condition: service_healthy
        restart: true
    env_file:
      - business_owner/config/auth-config.env
    environment:
      - POSTGRES_HOST=postgres_database
    networks:
      - kong-net

  kong-migrations:
    image: "${KONG_DOCKER_TAG:-kong:latest}"
    command: kong migrations bootstrap
    depends_on:
      - db
    environment:
      KONG_DATABASE: postgres
      KONG_PG_DATABASE: ${KONG_PG_DATABASE:-kong}
      KONG_PG_HOST: db
      KONG_PG_USER: ${KONG_PG_USER:-kong}
      KONG_PG_PASSWORD_FILE: /run/secrets/kong_postgres_password
    secrets:
      - kong_postgres_password
    networks:
      - kong-net
    restart: on-failure
    deploy:
      restart_policy:
        condition: on-failure

  kong-migrations-up:
    image: "${KONG_DOCKER_TAG:-kong:latest}"
    command: kong migrations up && kong migrations finish
    depends_on:
      - db
    environment:
      KONG_DATABASE: postgres
      KONG_PG_DATABASE: ${KONG_PG_DATABASE:-kong}
      KONG_PG_HOST: db
      KONG_PG_USER: ${KONG_PG_USER:-kong}
      KONG_PG_PASSWORD_FILE: /run/secrets/kong_postgres_password
    secrets:
      - kong_postgres_password
    networks:
      - kong-net
    restart: on-failure
    deploy:
      restart_policy:
        condition: on-failure

  kong:
    container_name: kong
    image: "${KONG_DOCKER_TAG:-kong:latest}"
    user: "${KONG_USER:-kong}"
    depends_on:
      - db
    environment:
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_PROXY_LISTEN: "${KONG_PROXY_LISTEN:-0.0.0.0:8000}"
      KONG_ADMIN_LISTEN: "${KONG_ADMIN_LISTEN:-0.0.0.0:8001}"
      KONG_ADMIN_GUI_LISTEN: "${KONG_ADMIN_GUI_LISTEN:-0.0.0.0:8002}"
      KONG_CASSANDRA_CONTACT_POINTS: db
      KONG_DATABASE: postgres
      KONG_PG_DATABASE: ${KONG_PG_DATABASE:-kong}
      KONG_PG_HOST: db
      KONG_PG_USER: ${KONG_PG_USER:-kong}
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_PG_PASSWORD_FILE: /run/secrets/kong_postgres_password
    secrets:
      - kong_postgres_password
    networks:
      - kong-net
    ports:
      - "8000:8000/tcp"
      - "8001:8001/tcp"
      - "8002:8002/tcp"
      - "8443:8443/tcp"
      - "127.0.0.1:8444:8444/tcp"
    healthcheck:
      test: ["CMD", "kong", "health"]
      interval: 10s
      timeout: 10s
      retries: 10
    restart: on-failure:5
    deploy:
      restart_policy:
        condition: on-failure

  db:
    image: postgres:9.5
    environment:
      POSTGRES_DB: ${KONG_PG_DATABASE:-kong}
      POSTGRES_USER: ${KONG_PG_USER:-kong}
      POSTGRES_PASSWORD_FILE: /run/secrets/kong_postgres_password
    secrets:
      - kong_postgres_password
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${KONG_PG_USER:-kong}"]
      interval: 30s
      timeout: 30s
      retries: 3
    restart: on-failure
    deploy:
      restart_policy:
        condition: on-failure
    stdin_open: true
    tty: true
    networks:
      - kong-net
    volumes:
      - kong_data:/var/lib/postgresql/data

networks:
  kong-net:
    external: false

secrets:
  kong_postgres_password:
    file: ./POSTGRES_PASSWORD