// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/GabrielMoody/MikroNet/services/order/internal/model"
	mock "github.com/stretchr/testify/mock"

	redis "github.com/redis/go-redis/v9"
)

// OrderRepo is an autogenerated mock type for the OrderRepo type
type OrderRepo struct {
	mock.Mock
}

// ConfirmOrder provides a mock function with given fields: c, order
func (_m *OrderRepo) ConfirmOrder(c context.Context, order model.Order) (model.Order, error) {
	ret := _m.Called(c, order)

	if len(ret) == 0 {
		panic("no return value specified for ConfirmOrder")
	}

	var r0 model.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.Order) (model.Order, error)); ok {
		return rf(c, order)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.Order) model.Order); ok {
		r0 = rf(c, order)
	} else {
		r0 = ret.Get(0).(model.Order)
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.Order) error); ok {
		r1 = rf(c, order)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindNearestDriver provides a mock function with given fields: c, pickup_point
func (_m *OrderRepo) FindNearestDriver(c context.Context, pickup_point model.GeoPoint) ([]redis.GeoLocation, error) {
	ret := _m.Called(c, pickup_point)

	if len(ret) == 0 {
		panic("no return value specified for FindNearestDriver")
	}

	var r0 []redis.GeoLocation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.GeoPoint) ([]redis.GeoLocation, error)); ok {
		return rf(c, pickup_point)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.GeoPoint) []redis.GeoLocation); ok {
		r0 = rf(c, pickup_point)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]redis.GeoLocation)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.GeoPoint) error); ok {
		r1 = rf(c, pickup_point)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MakeOrder provides a mock function with given fields: c, order
func (_m *OrderRepo) MakeOrder(c context.Context, order model.Order) (model.Order, error) {
	ret := _m.Called(c, order)

	if len(ret) == 0 {
		panic("no return value specified for MakeOrder")
	}

	var r0 model.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.Order) (model.Order, error)); ok {
		return rf(c, order)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.Order) model.Order); ok {
		r0 = rf(c, order)
	} else {
		r0 = ret.Get(0).(model.Order)
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.Order) error); ok {
		r1 = rf(c, order)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewOrderRepo creates a new instance of OrderRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOrderRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *OrderRepo {
	mock := &OrderRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
