name: Deployment Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        id: docker-hub
        env:
          username: ${{secrets.DOCKER_HUB_USERNAME}}
          password: ${{secrets.DOCKER_HUB_PASSWORD}}
        run: |
          docker login -u $username -p $password

      - name: Get list of updated folders
        id: changes
        run: |
          UPDATED_FOLDERS=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | awk -F'/' '{print $1}' | sort -u)
          echo "Updated folders: $UPDATED_FOLDERS"
          echo "folders=$UPDATED_FOLDERS" >> $GITHUB_ENV

      - name: Build docker image
        id: build-docker-image
        run: |
            for folder in ${{ env.folders }}; do
                docker build -t ${{secrets.DOCKER_HUB_USERNAME}}/$folder:latest $folder
            done

      - name: Push the docker image
        id: push-docker-image
        run: |
            for folder in ${{ env.folders }}; do
                docker push ${{secrets.DOCKER_HUB_USERNAME}}/$folder:latest
            done

      - name: Deploy with SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          key: ${{ secrets.SSH_KEY }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          script: |
            echo "${{ secrets.SSH_PASSWORD }}" | sudo -S docker-compose up -d --pull always