name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - image: gabrielmoody/authentication
            dockerfile: authentication/Dockerfile
          - image: gabrielmoody/profiles
            dockerfile: profiles/Dockerfile
          - image: gabrielmoody/notification
            dockerfile: notification/Dockerfile
          - image: gabrielmoody/driver
            dockerfile: driver/Dockerfile
          - image: gabrielmoody/geolocation_tracking
            dockerfile: geolocation_tracking/Dockerfile

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Login to Docker Hub
      id: docker-hub
      env:
        username: ${{secrets.DOCKER_HUB_USERNAME}}
        password: ${{secrets.DOCKER_HUB_PASSWORD}}
      run: |
        docker login -u $username -p $password

    - name: build docker image
      id: build-docker-image
      run: |
        docker build authentication -f Dockerfile -t gabrielmoody/authentication:latest
        docker build driver -f Dockerfile -t gabrielmoody/driver:latest
        docker build geolocation_tracking -f Dockerfile -t gabrielmoody/geolocation_tracking:latest
        docker build profiles -f Dockerfile -t gabrielmoody/profiles:latest
        docker build user -f Dockerfile -t gabrielmoody/user:latest
        
    - name: Push the docker image
      id: push-docker-image
      run: |
        docker push ${{secrets.DOCKER_HUB_USERNAME}}/authentication:latest
        docker push ${{secrets.DOCKER_HUB_USERNAME}}/driver:latest
        docker push ${{secrets.DOCKER_HUB_USERNAME}}/user:latest
        docker push ${{secrets.DOCKER_HUB_USERNAME}}/profiles:latest
        docker push ${{secrets.DOCKER_HUB_USERNAME}}/geolocation_tracking:latest