name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - image: gabrielmoody/authentication
            dockerfile: authentication/Dockerfile
          - image: gabrielmoody/profiles
            dockerfile: profiles/Dockerfile
          - image: gabrielmoody/notification
            dockerfile: notification/Dockerfile
          - image: gabrielmoody/driver
            dockerfile: driver/Dockerfile
          - image: gabrielmoody/geolocation_tracking
            dockerfile: geolocation_tracking/Dockerfile

    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with: 
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: ${{ matrix.image }}

    - name: Build and Push Image
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ${{ matrix.dockerfile }}
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

    
